#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__

#define MW_MULTI_TASKING_MODE 0

#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE Android Device
#define MW_CONNECTIONINFO_TCPIP_IPADDRESS codertarget.android.internal.getDeviceIPAddressParameter
#define MW_CONNECTIONINFO_TCPIP_PORT 17725
#define MW_CONNECTIONINFO_TCPIP_VERBOSE 0
#define MW_EXTMODE_CONFIGURATION TCP/IP
#define MW_EXTMODE_RUNNING on
#define MW_RTOS Android
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION -1
#define MW_PACKAGE_NAME com.example
#define MW_THINGSPEAK_ENABLECUSTOMSERVER 48
#define MW_THINGSPEAK_IPADDRESS 184.106.153.149
#define MW_THINGSPEAK_PORT 80
#define MW_SERIAL_SERIAL0_BAUD_RATE 3
#define MW_UI_SCALEORSCROLL 0
#define MW_SIMULINKIO_ENABLE_SIMULINKIO 1
#define MW_SIMULINKIO_TRANSPORTLAYERTYPE 0
#define MW_SIMULINKIO_MODELTRANSPORTDATAFCN codertarget.android.ioclient.getModelTransportInfo
#define MW_SIMULINKIO_SERVERDEPLOYFCN codertarget.android.ioclient.deployServer
#define MW_SIMULINKIO_SERVERSTOPFCN codertarget.android.ioclient.stopServer
#define MW_DATAVERSION 2016.02
#define MW_DASHBOARDCODEGENINFO_CIRCULARGAUGE_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_CIRCULARGAUGE_BLOCKCLASS codertarget.internal.androidCircularGauge
#define MW_DASHBOARDCODEGENINFO_CIRCULARGAUGE_REGFCN codertarget.internal.androidRegisterDashboardBlk
#define MW_DASHBOARDCODEGENINFO_CIRCULARGAUGE_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_SEMICIRCULARGAUGE_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_SEMICIRCULARGAUGE_BLOCKCLASS codertarget.internal.androidSemiCircularGauge
#define MW_DASHBOARDCODEGENINFO_SEMICIRCULARGAUGE_REGFCN codertarget.internal.androidRegisterDashboardBlk
#define MW_DASHBOARDCODEGENINFO_SEMICIRCULARGAUGE_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_QUARTERGAUGE_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_QUARTERGAUGE_BLOCKCLASS codertarget.internal.androidQuarterGauge
#define MW_DASHBOARDCODEGENINFO_QUARTERGAUGE_REGFCN codertarget.internal.androidRegisterDashboardBlk
#define MW_DASHBOARDCODEGENINFO_QUARTERGAUGE_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_KNOB_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_KNOB_BLOCKCLASS codertarget.internal.androidKnob
#define MW_DASHBOARDCODEGENINFO_KNOB_REGFCN codertarget.internal.androidRegisterDashboardSourceBlock
#define MW_DASHBOARDCODEGENINFO_KNOB_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_SLIDERSWITCH_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_SLIDERSWITCH_BLOCKCLASS codertarget.internal.androidSliderSwitch
#define MW_DASHBOARDCODEGENINFO_SLIDERSWITCH_REGFCN codertarget.internal.androidRegisterDashboardSourceBlock
#define MW_DASHBOARDCODEGENINFO_SLIDERSWITCH_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_TOGGLESWITCH_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_TOGGLESWITCH_BLOCKCLASS codertarget.internal.androidToggleSwitch
#define MW_DASHBOARDCODEGENINFO_TOGGLESWITCH_REGFCN codertarget.internal.androidRegisterDashboardSourceBlock
#define MW_DASHBOARDCODEGENINFO_TOGGLESWITCH_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_ROCKERSWITCH_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_ROCKERSWITCH_BLOCKCLASS codertarget.internal.androidRockerSwitch
#define MW_DASHBOARDCODEGENINFO_ROCKERSWITCH_REGFCN codertarget.internal.androidRegisterDashboardSourceBlock
#define MW_DASHBOARDCODEGENINFO_ROCKERSWITCH_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_SLIDER_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_SLIDER_BLOCKCLASS codertarget.internal.androidDashboardSlider
#define MW_DASHBOARDCODEGENINFO_SLIDER_REGFCN codertarget.internal.androidRegisterDashboardSourceBlock
#define MW_DASHBOARDCODEGENINFO_SLIDER_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen
#define MW_DASHBOARDCODEGENINFO_LAMP_CODEGEN 1
#define MW_DASHBOARDCODEGENINFO_LAMP_BLOCKCLASS codertarget.internal.androidLamp
#define MW_DASHBOARDCODEGENINFO_LAMP_REGFCN codertarget.internal.androidRegisterDashboardBlk
#define MW_DASHBOARDCODEGENINFO_LAMP_VALIDATEFCN codertarget.internal.androidIsDashboardBlockValidForCodegen

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
